apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: eks
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "a1dd33768b4bc4d1b824dbf3cc0b4618-3803c5dbb391219b.elb.ap-south-1.amazonaws.com"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: secretsManager
  vault: {}
  webhook: lighthouse
